"""add app usage hourly bucket table

Revision ID: 414f0e2633b2
Revises: b68077ca4f4d
Create Date: 2026-07-17 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '414f0e2633b2'
down_revision: Union[str, None] = 'b68077ca4f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appusagehourlybucket',
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'package_name', 'local_date', 'hour')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appusagehourlybucket')
    # ### end Alembic commands ###
