"""add child avatar and app icon columns

Revision ID: 4fd73b3a195e
Revises: c138c6c14e9d
Create Date: 2026-07-13 23:17:31.378862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fd73b3a195e'
down_revision: Union[str, None] = 'c138c6c14e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apprule', sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('child', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'avatar_url')
    op.drop_column('apprule', 'icon_url')
    # ### end Alembic commands ###
