"""add auto revoke bonus time column

Revision ID: 79a2f42a2a80
Revises: 4fd73b3a195e
Create Date: 2026-07-16 08:18:05.782654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79a2f42a2a80'
down_revision: Union[str, None] = '4fd73b3a195e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('auto_revoke_bonus_time', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'auto_revoke_bonus_time')
    # ### end Alembic commands ###
