"""initial schema

Revision ID: 85ff7bc4ad02
Revises: 
Create Date: 2026-07-12 23:07:37.542421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85ff7bc4ad02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('child',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollfailure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pollfailure_occurred_at'), 'pollfailure', ['occurred_at'], unique=False)
    op.create_table('changeevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changeevent_child_id'), 'changeevent', ['child_id'], unique=False)
    op.create_index(op.f('ix_changeevent_detected_at'), 'changeevent', ['detected_at'], unique=False)
    op.create_index(op.f('ix_changeevent_field_path'), 'changeevent', ['field_path'], unique=False)
    op.create_table('latestsnapshot',
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('child_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latestsnapshot')
    op.drop_index(op.f('ix_changeevent_field_path'), table_name='changeevent')
    op.drop_index(op.f('ix_changeevent_detected_at'), table_name='changeevent')
    op.drop_index(op.f('ix_changeevent_child_id'), table_name='changeevent')
    op.drop_table('changeevent')
    op.drop_index(op.f('ix_pollfailure_occurred_at'), table_name='pollfailure')
    op.drop_table('pollfailure')
    op.drop_table('child')
    op.drop_table('appsetting')
    # ### end Alembic commands ###
